services:
  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/db:/app/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - frontend_build:/usr/share/nginx/html
    depends_on:
      - backend
    restart: on-failure

  frontend_builder:
    build: ./frontend
    container_name: frontend
    volumes:
      - frontend_build:/usr/share/nginx/html

volumes:
  frontend_build: